GOFER-2020-consolidation-article
arup-group/gofer-news pull request #19
Opened 2024-05-09 13:08 UTC by ajha0112

Contents of this article reviewed and approved by Matt

2024-05-14 09:51 UTC, Alvaro-Rodrigueez approved these changes

2024-05-14 12:41 UTC, juliaklusek requested changes
Metadata doesn't match the article

2024-05-14 12:44 UTC, juliaklusek requested changes
Metadata doesn't match the article

2024-05-15 08:57 UTC, elizabethcbailey commented on news/journey-ahead/metadata.json
> +    "created": "2024-02-14"
```suggestion
    "created": "2024-05-14"
```

2024-05-15 09:06 UTC, juliaklusek approved these changes

2024-05-15 09:17 UTC, merged