GOFER-2545 Level up webinar news article
arup-group/gofer-news pull request #23
Opened 2024-10-10 11:40 UTC by elizabethcbailey

2024-10-10 15:29 UTC, elizabethcbailey commented on news/level-up-webinar/details.md
> +Designed for geotechnical engineers of all experience levels, Gofer is user-friendly and accelerates skill development with readily available tutorials, example models, and updated documentation. Lea
```suggestion
Designed for geotechnical engineers of all experience levels, Gofer is user-friendly and accelerates skill development with readily available tutorials, example models, and updated documentation. Learn more and see Gofer hard at work during our free webinar. Click [here](https://events.teams.microsoft.com/event/cab45c61-c5f8-4ff6-aa2c-114629ea3818@4ae48b41-0137-4599-8661-fc641fe77bea) to register. 
```

2024-10-11 08:13 UTC, MatthewBrownArup approved these changes

2024-10-11 08:15 UTC, MatthewBrownArup commented
@Carol-Matthews can you merge in Ellie's absence? Thanks.

2024-10-14 08:14 UTC, Carol-Matthews approved these changes

2024-10-14 08:27 UTC, juliaklusek requested changes
The title needs to be slightly shorter

2024-10-14 08:27 UTC, juliaklusek commented on news/level-up-webinar/metadata.json
> +    "title": "Level Up Your FEA with Oasys Gofer! - Webinar",
This title is too long. It will take up two lines in a news card. Can we remove the word "webinar" or "oasys"?

![too long](https://github.com/user-attachments/assets/e494946c-c4b5-47ba-a368-f76b9067916a)

2024-10-14 08:29 UTC, MatthewBrownArup commented on news/level-up-webinar/metadata.json
> +    "title": "Level Up Your FEA with Oasys Gofer! - Webinar",
Let's remove "Oasys"

2024-10-14 08:52 UTC, elizabethcbailey commented on news/level-up-webinar/metadata.json
> +    "title": "Level Up Your FEA with Oasys Gofer! - Webinar",
```suggestion
    "title": "Level Up Your FEA with Gofer! - Webinar",
```

2024-10-14 08:53 UTC, juliaklusek approved these changes

2024-10-14 08:57 UTC, Carol-Matthews approved these changes

2024-10-14 08:57 UTC, merged