Adding images to first four news articles
arup-group/gofer-news pull request #7
Opened 2023-10-16 13:59 UTC by elizabethcbailey

One image per page.

2023-10-16 14:23 UTC, Alvaro-Rodrigueez requested changes

2023-10-16 14:23 UTC, Alvaro-Rodrigueez commented on news/NUMGE/details.md
> +![Happy Birthday Gofer](https://b2c-templates-arup.s3-eu-west-1.amazonaws.com/gofer/NUMGE_image.svg)
The image name here is 'Happy Birthday Gofer' but it's related to NUMGE and not the birthday

2023-10-16 14:23 UTC, Alvaro-Rodrigueez commented on news/smart-geo/details.md
> +![Happy Birthday Gofer](https://b2c-templates-arup.s3-eu-west-1.amazonaws.com/gofer/Smart_Geo_Image_Gofer.svg)
Same here, wrong image name

2023-10-17 08:21 UTC, elizabethcbailey commented on news/smart-geo/details.md
> +![Happy Birthday Gofer](https://b2c-templates-arup.s3-eu-west-1.amazonaws.com/gofer/Smart_Geo_Image_Gofer.svg)
sorry about that Alvaro! Thanks so much for catching that! I have updated the names on a second commit on this PR.

2023-10-17 08:57 UTC, Alvaro-Rodrigueez approved these changes

2023-10-17 08:57 UTC, merged